FROM registry.fedoraproject.org/fedora-toolbox:41

# Needed packages
RUN dnf -y distro-sync && \
    dnf -y install \
    helix \
    zsh \
    keychain \
    direnv \
    sqlite3 \
    fd-find \
    ripgrep \
    cmake \
    libtool \
    java-11-openjdk \
    eza \
    bat \
    cargo \
    cmake \
    direnv \
    enchant2-devel \
    pkgconf \
    rlwrap \
    gh \
    jq \
    autoconf \
    automake \
    gcc \
    python \
    shellcheck \
    shfmt \
    nodejs \
    yarnpkg \
    unzip \
    p7zip \
    git \
    --exclude=nodejs-docs,nodejs-full-il8n,btrfs-progs,systemd-networkd && \
    dnf clean all

# Setup global aliases for host-spawn
RUN  ln -s /usr/bin/distrobox-host-exec /usr/local/bin/distrobox && \
    ln -s /usr/bin/distrobox-host-exec /usr/local/bin/flatpak && \
    ln -s /usr/bin/distrobox-host-exec /usr/local/bin/podman && \
    ln -s /usr/bin/distrobox-host-exec /usr/local/bin/pw-mon && \
    ln -s /usr/bin/distrobox-host-exec /usr/local/bin/swaymsg && \
    ln -s /usr/bin/distrobox-host-exec /usr/local/bin/sway && \
    ln -s /usr/bin/distrobox-host-exec /usr/local/bin/swaync-client && \
    ln -s /usr/bin/distrobox-host-exec /usr/local/bin/xdg-open

# Setup Clojure
RUN curl -L -O https://github.com/clojure/brew-install/releases/latest/download/linux-install.sh && \
    chmod +x linux-install.sh && \
    ./linux-install.sh && \
    rm linux-install.sh

# Copy files useful for scripts
COPY --from=ghcr.io/babashka/babashka:latest /usr/local/bin/bb /usr/bin/bb
COPY --from=ghcr.io/charmbracelet/gum:latest /usr/local/bin/gum /usr/bin/gum

# Install important typst packages
RUN cargo install --git https://github.com/nvarner/typst-lsp.git typst-lsp && \
    cargo install --git https://github.com/astrale-sharp/typstfmt.git
