FROM archlinux:base-devel

RUN pacman -Sy --noconfirm sudo git keychain direnv eza bat lsb-release cargo && \
    cargo install aura-pm && \
    ln -s ~/.cargo/bin/aura /usr/local/bin/aura

# Do this after makepkg so we don't need the key
COPY etc /etc
