FROM archlinux:base-devel
MAINTAINER Ellis Kenyő <me@elken.dev>

RUN pacman -Sy --noconfirm sudo git keychain direnv exa bat lsb-release cargo && \
    cargo install aura-pm --version 4.0.0-alpha9 && \
    ln -s ~/.cargo/bin/aura /usr/local/bin/aura

# Do this after makepkg so we don't need the key
COPY etc /etc
